import product1 from '../../../asset/images/image11.jpg';
import product2 from '../../../asset/images/image12.jpg';

export const products = [
  {
    id: 1,
    name: "Fresh Hen Eggs",
    categoryName: "Animals",
    price: 12000,
    originalPrice: 15000,
    aggregate: 50,
    rating: 4.5,
    reviewCount: 34,
    imageURL: product2,
    seller: "GreenFarm Supplies",
    description: "Premium fresh hen eggs sourced directly from free-range hens. Rich in protein and nutrients. Perfect for households, restaurants, and bakeries.",
    specifications: [
      { label: "Type", value: "Free Range Eggs" },
      { label: "Pack Size", value: "30 Eggs" },
      { label: "Origin", value: "Nakuru, Kenya" },
      { label: "Storage", value: "Cool, dry place" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
  {
    id: 2,
    name: "Maize (1 Bag 90kg)",
    categoryName: "Grains",
    price: 3000,
    originalPrice: 3800,
    aggregate: 100,
    rating: 4.2,
    reviewCount: 21,
    imageURL: product1,
    seller: "AgriMart Kenya",
    description: "High quality dry maize grain, well sorted and free from impurities. Suitable for milling, animal feeds, and direct consumption.",
    specifications: [
      { label: "Weight", value: "90 kg per bag" },
      { label: "Moisture", value: "Below 13.5%" },
      { label: "Origin", value: "Eldoret, Kenya" },
      { label: "Grade", value: "Grade 1" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
  {
    id: 3,
    name: "Broiler Chicks (50 pcs)",
    categoryName: "Animals",
    price: 8500,
    originalPrice: 10000,
    aggregate: 30,
    rating: 4.3,
    reviewCount: 18,
    imageURL: product2,
    seller: "NaivashaCoop",
    description: "Healthy day-old broiler chicks, vaccinated and ready for rearing. High growth rate, ideal for commercial poultry farming.",
    specifications: [
      { label: "Breed", value: "Broiler" },
      { label: "Age", value: "Day Old" },
      { label: "Vaccination", value: "Marek's + Newcastle" },
      { label: "Origin", value: "Naivasha, Kenya" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
  {
    id: 4,
    name: "Wheat Flour (50kg)",
    categoryName: "Grains",
    price: 2200,
    originalPrice: 2800,
    aggregate: 80,
    rating: 4.0,
    reviewCount: 15,
    imageURL: product1,
    seller: "CerealsKenya",
    description: "Finely milled wheat flour, perfect for baking bread, chapati, and other pastries. Processed under hygienic conditions.",
    specifications: [
      { label: "Weight", value: "50 kg per bag" },
      { label: "Type", value: "All Purpose Flour" },
      { label: "Origin", value: "Nairobi, Kenya" },
      { label: "Grade", value: "Grade A" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
  {
    id: 5,
    name: "Dairy Goat (Female)",
    categoryName: "Animals",
    price: 22000,
    originalPrice: 25000,
    aggregate: 10,
    rating: 4.7,
    reviewCount: 9,
    imageURL: product2,
    seller: "KilimoFresh",
    description: "High-yield dairy goat producing up to 3 litres per day. Healthy, well-fed, and ready for immediate milking. Alpine-Toggenburg cross breed.",
    specifications: [
      { label: "Breed", value: "Alpine-Toggenburg Cross" },
      { label: "Milk Yield", value: "2–3 L/day" },
      { label: "Age", value: "2 years" },
      { label: "Origin", value: "Nyeri, Kenya" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
  {
    id: 6,
    name: "Sorghum (1 Bag 90kg)",
    categoryName: "Grains",
    price: 2500,
    originalPrice: 3200,
    aggregate: 60,
    rating: 3.9,
    reviewCount: 11,
    imageURL: product1,
    seller: "MkulimaMart",
    description: "Organic sorghum grains, drought-tolerant and rich in minerals. Ideal for animal feeds, local brew production, and food processing.",
    specifications: [
      { label: "Weight", value: "90 kg per bag" },
      { label: "Type", value: "Organic Sorghum" },
      { label: "Origin", value: "Machakos, Kenya" },
      { label: "Grade", value: "Grade 2" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
  {
    id: 7,
    name: "Kienyeji Chicken (Live)",
    categoryName: "Animals",
    price: 1500,
    originalPrice: 1800,
    aggregate: 40,
    rating: 4.6,
    reviewCount: 27,
    imageURL: product2,
    seller: "GreenFarm Supplies",
    description: "Mature free-range Kienyeji chicken, well-fed on natural feeds. Perfect for roasting, stewing, or starting your own poultry flock.",
    specifications: [
      { label: "Type", value: "Free-range Kienyeji" },
      { label: "Weight", value: "1.8 – 2.5 kg" },
      { label: "Age", value: "6 months" },
      { label: "Origin", value: "Nakuru, Kenya" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
  {
    id: 8,
    name: "Barley (1 Bag 90kg)",
    categoryName: "Grains",
    price: 3500,
    originalPrice: 4200,
    aggregate: 45,
    rating: 4.1,
    reviewCount: 8,
    imageURL: product1,
    seller: "AgriMart Kenya",
    description: "Premium quality barley grain, clean and well-dried. Suitable for animal feeds, malting, and food production.",
    specifications: [
      { label: "Weight", value: "90 kg per bag" },
      { label: "Moisture", value: "Below 12%" },
      { label: "Origin", value: "Timau, Kenya" },
      { label: "Grade", value: "Grade 1" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
  {
    id: 9,
    name: "Fresh Hen Eggs (Tray)",
    categoryName: "Animals",
    price: 450,
    originalPrice: 550,
    aggregate: 200,
    rating: 4.4,
    reviewCount: 52,
    imageURL: product2,
    seller: "GreenFarm Supplies",
    description: "Farm-fresh tray of 30 eggs from cage-free hens. Rich golden yolks, thin shells, and superior freshness guaranteed.",
    specifications: [
      { label: "Type", value: "Cage Free Eggs" },
      { label: "Pack Size", value: "30 Eggs" },
      { label: "Origin", value: "Nakuru, Kenya" },
      { label: "Storage", value: "Refrigerate below 4°C" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
  {
    id: 10,
    name: "Tilapia Fish (5kg)",
    categoryName: "Fisheries",
    price: 1800,
    originalPrice: 2200,
    aggregate: 25,
    rating: 4.3,
    reviewCount: 19,
    imageURL: product1,
    seller: "AgriMart Kenya",
    description: "Fresh tilapia fish sourced from certified fish ponds. Cleaned and ready for cooking. High protein content and rich omega-3 fatty acids.",
    specifications: [
      { label: "Weight", value: "5 kg" },
      { label: "Type", value: "Fresh Water Tilapia" },
      { label: "Origin", value: "Kisumu, Kenya" },
      { label: "Storage", value: "Keep refrigerated" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
  {
    id: 11,
    name: "Rabbit (Breeding Pair)",
    categoryName: "Animals",
    price: 3200,
    originalPrice: 4000,
    aggregate: 15,
    rating: 4.5,
    reviewCount: 13,
    imageURL: product2,
    seller: "AgriMart Kenya",
    description: "Healthy California-breed rabbit breeding pair. Fast-growing, easy to rear, and ideal for meat production or starting a rabbitry.",
    specifications: [
      { label: "Breed", value: "California White" },
      { label: "Age", value: "3 months" },
      { label: "Sex", value: "1 Male + 1 Female" },
      { label: "Origin", value: "Naivasha, Kenya" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
  {
    id: 12,
    name: "Rice (1 Bag 50kg)",
    categoryName: "Grains",
    price: 4500,
    originalPrice: 5200,
    aggregate: 70,
    rating: 4.6,
    reviewCount: 30,
    imageURL: product1,
    seller: "NaivashaCoop",
    description: "Premium long-grain rice, clean, polished, and stone-free. Cooks fluffy and aromatic. Ideal for homes, hotels, and restaurants.",
    specifications: [
      { label: "Weight", value: "50 kg per bag" },
      { label: "Type", value: "Long Grain White Rice" },
      { label: "Origin", value: "Mwea, Kenya" },
      { label: "Grade", value: "Grade 1" },
    ],
    deliveryOptions: [
      { type: "Instant Delivery", price: 400 },
      { type: "Pickup Station", price: 70 },
      { type: "Door Delivery", price: 160 },
    ],
  },
];
